global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'release-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['release-service:8080', 'host.docker.internal:8080']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8081', 'host.docker.internal:8081']
